sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tPjKq1nuvsofNhorN7K
    accessKeySecret: AKPNopgrmMWW6j8OgUwbPnLKEJugZY
    bucketName: byeworld